package hook

import (
	"sort"
	"sync"

	"github.com/lumm2509/keel/infra/security"
)

// Handler defines a single Hook handler.
// Multiple handlers can share the same id.
// If Id is not explicitly set it will be autogenerated by Hook.Add and Hook.AddHandler.
type Handler[T Resolver] struct {
	// Func defines the handler function to execute.
	//
	// Note that users need to call e.Next() in order to proceed with
	// the execution of the hook chain.
	Func func(T) error

	// Id is the unique identifier of the handler.
	//
	// It could be used later to remove the handler from a hook via [Hook.Remove].
	//
	// If missing, an autogenerated value will be assigned when adding
	// the handler to a hook.
	Id string

	// Priority allows changing the default exec priority of the handler within a hook.
	//
	// If 0, the handler will be executed in the same order it was registered.
	Priority int
}

// Hook defines a generic concurrent safe structure for managing event hooks.
//
// When using custom event it must embed the base [hook.Event].
//
// Example:
//
//	type CustomEvent struct {
//		hook.Event
//		SomeField int
//	}
//
//	h := Hook[*CustomEvent]{}
//
//	h.BindFunc(func(e *CustomEvent) error {
//		println(e.SomeField)
//
//		return e.Next()
//	})
//
//	h.Trigger(&CustomEvent{ SomeField: 123 })
type Hook[T Resolver] struct {
	handlers []*Handler[T]
	mu       sync.RWMutex
}

type nextStateSetter interface {
	setNextState(nextInvoker)
}

type triggerState[T Resolver] struct {
	event     T
	handlers  []*Handler[T]
	oneOff    []func(T) error
	nextIndex int
}

func (s *triggerState[T]) next() error {
	if s.nextIndex < len(s.handlers) {
		handler := s.handlers[s.nextIndex]
		s.nextIndex++
		return handler.Func(s.event)
	}

	oneOffIndex := s.nextIndex - len(s.handlers)
	if oneOffIndex >= len(s.oneOff) {
		return nil
	}

	s.nextIndex++
	return s.oneOff[oneOffIndex](s.event)
}

// Bind registers the provided handler to the current hooks queue.
//
// If handler.Id is empty it is updated with autogenerated value.
//
// If a handler from the current hook list has Id matching handler.Id
// then the old handler is replaced with the new one.
func (h *Hook[T]) Bind(handler *Handler[T]) string {
	h.mu.Lock()
	defer h.mu.Unlock()

	if handler.Id == "" {
		handler.Id = generateHookId()

		// ensure that it doesn't exist
	DUPLICATE_CHECK:
		for _, existing := range h.handlers {
			if existing.Id == handler.Id {
				handler.Id = generateHookId()
				goto DUPLICATE_CHECK
			}
		}
	}

	handlers := append([]*Handler[T](nil), h.handlers...)
	insertAt := len(handlers)

	if handler.Id != "" {
		for i, existing := range handlers {
			if existing.Id == handler.Id {
				handlers = append(handlers[:i], handlers[i+1:]...)
				if i < insertAt {
					insertAt = i
				}
				break
			}
		}
	}

	for i, existing := range handlers {
		if existing.Priority > handler.Priority {
			insertAt = i
			break
		}
	}

	handlers = append(handlers, nil)
	copy(handlers[insertAt+1:], handlers[insertAt:])
	handlers[insertAt] = handler
	h.handlers = handlers

	return handler.Id
}

// BindFunc is similar to Bind but registers a new handler from just the provided function.
//
// The registered handler is added with a default 0 priority and the id will be autogenerated.
//
// If you want to register a handler with custom priority or id use the [Hook.Bind] method.
func (h *Hook[T]) BindFunc(fn func(e T) error) string {
	return h.Bind(&Handler[T]{Func: fn})
}

// SetHandlers replaces the current hook handlers with a sorted shallow copy.
func (h *Hook[T]) SetHandlers(handlers []*Handler[T]) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.handlers = append([]*Handler[T](nil), handlers...)
	sort.SliceStable(h.handlers, func(i, j int) bool {
		return h.handlers[i].Priority < h.handlers[j].Priority
	})
}

// SetSortedHandlers replaces the current hook handlers with the provided slice as-is.
//
// The caller is responsible for providing a stable slice already sorted by Priority
// and for not mutating the slice after passing it to the hook.
func (h *Hook[T]) SetSortedHandlers(handlers []*Handler[T]) {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.handlers = handlers
}

// Unbind removes one or many hook handler by their id.
func (h *Hook[T]) Unbind(idsToRemove ...string) {
	h.mu.Lock()
	defer h.mu.Unlock()

	handlers := append([]*Handler[T](nil), h.handlers...)

	for _, id := range idsToRemove {
		for i := len(handlers) - 1; i >= 0; i-- {
			if handlers[i].Id == id {
				handlers = append(handlers[:i], handlers[i+1:]...)
				break // for now stop on the first occurrence since we don't allow handlers with duplicated ids
			}
		}
	}

	h.handlers = handlers
}

// UnbindAll removes all registered handlers.
func (h *Hook[T]) UnbindAll() {
	h.mu.Lock()
	defer h.mu.Unlock()

	h.handlers = nil
}

// Length returns to total number of registered hook handlers.
func (h *Hook[T]) Length() int {
	h.mu.RLock()
	defer h.mu.RUnlock()

	return len(h.handlers)
}

// Trigger executes all registered hook handlers one by one
// with the specified event as an argument.
//
// Optionally, this method allows also to register additional one off
// handler funcs that will be temporary appended to the handlers queue.
//
// NB! Each hook handler must call event.Next() in order the hook chain to proceed.
func (h *Hook[T]) Trigger(event T, oneOffHandlerFuncs ...func(T) error) error {
	h.mu.RLock()
	handlers := h.handlers
	h.mu.RUnlock()

	if statefulEvent, ok := any(event).(nextStateSetter); ok {
		statefulEvent.setNextState(&triggerState[T]{
			event:    event,
			handlers: handlers,
			oneOff:   oneOffHandlerFuncs,
		})
		return event.Next()
	}

	i := 0
	event.setNextFunc(func() error {
		if i < len(handlers) {
			handler := handlers[i]
			i++

			return handler.Func(event)
		}

		oneOffIndex := i - len(handlers)
		if oneOffIndex >= len(oneOffHandlerFuncs) {
			return nil
		}

		i++
		return oneOffHandlerFuncs[oneOffIndex](event)
	})

	return event.Next()
}

func generateHookId() string {
	return security.PseudorandomString(20)
}
